[versions]
# Reported security issue on https://github.com/FamilySearch/gedcom5-java/issues/37
# fixed in the upsteam project, but fix has yet to be released.
gedcom = "1.14.0"
cli = "0.3.6"
slf4j = "2.0.17"

[libraries]
familysearch-gedcom = { group = "org.familysearch.gedcom", name = "gedcom", version.ref = "gedcom" }
kotlinx-cli = { group = "org.jetbrains.kotlinx", name = "kotlinx-cli", version.ref = "cli" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }