name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.8)'
        required: true
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Pour push, tag, et release
      pull-requests: write  # Optionnel : si tu veux une PR pour la mise Ã  jour du README

    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump app version
        run: |
          sed -i "s/version = \".*\"/version = \"${{ inputs.version }}\"/g" build.gradle.kts
          git add build.gradle.kts
          git commit -m "build: bump version to ${{ inputs.version }}"
          git push

      - name: Create tag
        run: |
          git tag "v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"
          
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run unit tests
        run: ./gradlew test

      - name: Build distributions
        run: ./gradlew assembleDist --no-daemon

      - name: Create github release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ inputs.version }}"
          name: "Version ${{ inputs.version }}"
          draft: true
          generate_release_notes: true
          files: |
            build/distributions/*.tar.gz
            build/distributions/*.zip
